# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160331_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
