# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateField(blank=True),
        ),
    ]
