# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160402_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateField(),
        ),
    ]
